config/routes.rb
Rails.application.routes.draw do
  get "/" => "lists#new"
  root to: 'home#top'
  get 'lists/new'
  post 'books' => 'lists#create'   #ここを追記します
  get 'books' => 'lists#index'
  get 'lists/index'
  get 'show' => 'lists#show'
 
  get 'homes/top'
   
   # .../lists/1 や .../lists/3 に該当する
  
  get 'books/:id' => 'lists#show', as: 'book'
  get 'books/:id/edit' => 'lists#edit', as: 'edit_book'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  patch 'books/:id' => 'lists#update', as: 'update_list'
  delete 'books/:id' => 'lists#destroy', as: 'destroy_list'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
   
  end
# 以下を追加
  def create
    # １.&2. データを受け取り新規登録するためのインスタンス作成
    @book = Book.new(book_params)
    # 3. データをデータベースに保存するためのsaveメソッド実行
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end
  
  
  def index
    @book = Book.new
    @books = Book.all  
  end

  def show
    @book = Book.find(params[:id])  
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def destroy
    book = Book.find(params[:id])  # データ（レコード）を1件取得
    book.destroy  # データ（レコード）を削除
    redirect_to '/books'  # 投稿一覧画面へリダイレクト  
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book.id)  
    else
      render :edit
    end
  end
  private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/homes/top.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
  </head>
  <body>
    <h1>ようこそBookersへ！</h1>
    <p>Bookers では、さまざまな書籍に関するあなたの意見や</p>

<p>印象を共有し交換することができます</p>
<p>
  <a href = "/books"> start </a>
</p>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>Editing Book</h1>


    
<%= form_with model: @book, url: update_list_path(@book.id), method: :patch do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>
  
  <h4>Body</h4>
  <%= f.text_area :body %>
  
  <%= f.submit 'Update Book  ' %>
  <%= link_to "show", book_path(@book.id) %>
  <a href = "/books"> back </a>
  <% end %>
  
  <% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/lists/index.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
  </head>
  <body>
    <h1>Books</h1>
    <table>
      <thead>
        <tr>
        <th>Title</th>
            <th>Body</th>
            </tr>
            </thead>
<% @books.each do |book| %>
<tbody>
<tr>
 
  <td><%= book.title %>
  
  </td>

   <td><%= book.body %>
  
    </td>
    <td>
    <%= link_to "Show",book_path(book.id)  %>
   <%= link_to "Edit", edit_book_path(book.id)   %>
   <%= link_to "Destroy", destroy_list_path(book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
  </td>
   </tr>
  
<% end %>
    </tbody>

    </theadv>

    </table>
    
    
  <% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
    <h2>New book</h2>
    <!-- form_with部分 -->
<%= form_with model: @book do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
	
  <h4>Body</h4>
  <%= f.text_area :body %>
	
  <%= f.submit 'Create Book' %>
<% end %>

  </body>
</html>

app/views/lists/new.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
  </head>
  <body>
    <h1>ようこそBookersへ！</h1>
    <p>Bookers では、さまざまな書籍に関するあなたの意見や</p>

<p>印象を共有し交換することができます</p>
<p>
  <a href = "/books"> start </a>
</p>
  </body>
</html>

app/views/lists/show.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
  </head>
  <body>
    <%= flash[:notice] %>
   
<br>
<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>
<br>
<p>
  <strong>Body:</strong>
  <%= @book.body %>
</p>

  <%= link_to "edit", edit_book_path(@book.id)   %>
  <a href = "/books"> Back </a>
</p>
  </body>
</html>